### ISSUE TITLE
[Bug]Basic functionality isn't working well.

### ISSUE THREAD

**Issue by domnpp** [Novaturion/cpp-classes-creator#1]
Doesn't work at all, or works incorrectly.

Even right clicking the parent folder in explorer view and "Create C++ Class/Struct" creates new files in the wrong location (%USERPROFILE%\AppData\Local\Programs\Microsoft VS Code\<setting:C_Cpp.classesCreator.folder.defaultSourcesFolder>\newClassName.cpp)

I tried again, deleting setting:C_Cpp.classesCreator.folder.defaultSourcesFolder (and also header) fixed it partially - right clicking folder, create class works. Until this is fixed, I recomended everyone who uses this extension to use this approach instead (right click in Explorer in vscode).

**Comment by Novaturion** [comment]
Hi, can you try on new version please?
Just uploaded an update

**Comment by Novaturion** [comment]
@domenn, is issue still occurring?

**Comment by domnpp** [comment]
Yes. I also figured out where / how to view logs.

```
2023-11-16 18:32:46.707 [error] TypeError: getTransformedCase is not a function
	at applyCase (c:\Users\name\.vscode\extensions\novaturion.cpp-classes-creator-0.1.2\extension\extension.js:592:9)
	at addFiles (c:\Users\name\.vscode\extensions\novaturion.cpp-classes-creator-0.1.2\extension\extension.js:652:3)
	at c:\Users\name\.vscode\extensions\novaturion.cpp-classes-creator-0.1.2\extension\extension.js:191:11
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\name\.vscode\extensions\novaturion.cpp-classes-creator-0.1.2\extension\extension.js:100:20)
```

I right clico to the folder in explorer and click "New C++ class". I don't have source / header folder set in settings.json. nameCase is UpperCamelCase.

At the moment, due to the nature of my work, I don't have a need to use this extension anymore. That's also the reason for my late comment.
